"""Compiler-owned AO jets and density-invariant arithmetic for grid schedules.

The normalized native basis remains the only source of primitive and public AO
coefficients. The shared scalar DAG differentiates Gaussian polynomial factors
at build time; CUDA traversal, maps, buffers and matrix calls remain runtime.
"""

from vibeqc_compiler.common.paths import asset_path
from vibeqc_compiler.common.provenance import canonical_hash
from vibeqc_compiler.integral.cuda import CudaEmitter
from vibeqc_compiler.integral.expr import Graph

from .ao import jet_indices


def axis_expression(power, derivative):
    """Return exp(+a*x*x) d^d[x^l exp(-a*x*x)] as a scalar polynomial.

    Keeping the exponential outside avoids division by an underflowed radial
    factor. Derivatives are ordinary spatial derivatives, without factorials.
    """
    if (
        type(power) is not int
        or type(derivative) is not int
        or not (0 <= power <= 3 and 0 <= derivative <= 3)
    ):
        raise ValueError("AO axis domain is l,d in [0,3]")
    graph = Graph()
    x, a = graph.variable("x"), graph.variable("a")
    root = graph.constant(1)
    for _ in range(power):
        root = root * x
    for _ in range(derivative):
        root = graph.differentiate(root, x) - 2 * a * x * root
    return graph, root


def emit_grid_policy():
    """Emit through-f/order-three AO factors and spin feature contractions.

    The same policy serves dense and selected-column execution. Adding an AO
    domain needs a compiler change rather than another native scientific body.
    """
    lines = [
        "// Generated by vibeqc_compiler.dft.ao_cuda; do not edit.",
        "#include <cmath>",
        "namespace vibeqc_grid_policy {",
        "__device__ double axis_jet(int l, int d, double a, double x) {",
        "  switch (4*l+d) {",
    ]
    for power in range(4):
        for derivative in range(4):
            graph, root = axis_expression(power, derivative)
            emitter = CudaEmitter(graph, {})
            emitter.emit((root,))
            lines.append(f"  case {4 * power + derivative}: {{")
            lines.extend(emitter.lines)
            lines.extend((f"    return {emitter.reference(root)};", "  }"))
    lines.extend(("  }", "  return NAN;", "}"))
    domain = ",".join("{" + ",".join(map(str, d)) + "}" for d in jet_indices(3))
    lines.append(f"__constant__ int derivatives[20][3] = {{{domain}}};")
    graph = Graph()
    phi = graph.variable("phi")
    dp = tuple(graph.variable(f"derivative[{i}]") for i in range(3))
    work = tuple(graph.variable(f"work[{i}]") for i in range(4))
    roots = (
        phi * work[0],
        *(2 * d * work[0] for d in dp),
        sum((d * w / 2 for d, w in zip(dp, work[1:], strict=True)), graph.constant(0)),
    )
    emitter = CudaEmitter(graph, {})
    emitter.emit(roots)
    lines.append(
        "__device__ void add_features(double phi, const double* derivative, const double* work, double* accum) {"
    )
    lines.extend(emitter.lines)
    lines.extend(
        f"  accum[{i}] += {emitter.reference(r)};" for i, r in enumerate(roots)
    )
    lines.append("}")
    graph = Graph()
    gradients = [[graph.variable(f"g[{s}][{k}]") for k in range(3)] for s in range(2)]
    roots = tuple(
        sum((gradients[a][k] * gradients[b][k] for k in range(3)), graph.constant(0))
        for a, b in ((0, 0), (0, 1), (1, 1))
    )
    emitter = CudaEmitter(graph, {})
    emitter.emit(roots)
    lines.append("__device__ void sigma(const double (&g)[2][3], double* output) {")
    lines.extend(emitter.lines)
    lines.extend(
        f"  output[{i}] = {emitter.reference(r)};" for i, r in enumerate(roots)
    )
    lines.extend(("}", "}", ""))
    return "\n".join(lines)


def emit_grid_source():
    """Compose the generated policy with the existing native grid runtime."""
    policy = emit_grid_policy()
    source = policy + '#include "cuda_grid.cu"\n'
    return (
        source,
        canonical_hash({"schema": "vibeqc.grid-policy.v1", "source": source}),
        (
            asset_path("src/dft/cuda_grid.cu"),
            asset_path("src/tensor/cuda_runtime.cuh"),
            asset_path("src/dft/grid_task_view.cuh"),
        ),
    )
